# Generated by Django 6.0.6 on 2026-06-29 10:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('map_width', models.PositiveIntegerField(default=100)),
                ('map_height', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='starting', max_length=15)),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('max_players', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(2)])),
                ('is_private', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('starting', 'Starting'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='waiting', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_host', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.PositiveIntegerField(default=0)),
                ('deaths', models.PositiveIntegerField(default=0)),
                ('territory_percentage', models.DecimalField(decimal_places=4, max_digits=6)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='game.match')),
            ],
            options={
                'ordering': ['rank', 'kills', 'deaths'],
            },
        ),
    ]
