# Generated by Django 6.0.6 on 2026-06-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='map_size',
        ),
        migrations.AddField(
            model_name='match',
            name='map_height',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='match',
            name='map_width',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
