# Generated by Django 6.0.6 on 2026-06-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_match_map_size_match_map_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('starting', 'Starting'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='starting', max_length=15),
        ),
    ]
