# Generated by Django 6.0.6 on 2026-06-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_match_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['started_at']},
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
