# Generated by Django 6.0.6 on 2026-06-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_match_options_remove_match_winner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='territory_percentage',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
